name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23B7A57A&color_dots=%23ebedf0,%23ddd3e8,%2385759b,%234B2E83,%232B193D
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23B7A57A&color_dots=%23161b22,%23382748,%235c3b76,%234B2E83,%23B7A57A

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}